### PR TITLE
[BUGFIX] Make global scope available when running in Node.js land.

### PR DESCRIPTION
**Pull request by akoenig**
This PR contains a bugfix that resolves an `undefined` passed global variable
when running in a Node.js execution environment.

The problem was that the defined variable `global` overwrites the real "global" object
which causes an unmatched condition in the statement:

```js
else if (typeof global !== "undefined") {
    global = global;
```

`global` was in this case always `undefined`. This problem only occurs in the "unminified" artifact.
Anyway, this is a critical problem though. The tests (e.g. `assembler`) utilizes the unminified files.

### CODE REVIEW

**Comment by Inkdpixels** [comment]
Hey @akoenig - Thanks for the hard work again - But would you mind pointing this PR onto the development branch?

**Comment by akoenig** [comment]
Sure. I'm on a train with a very fragile internet connection. Therefore wasn't able to double check if there is already a dev branch. Will do when I'm back home.

**Comment by Inkdpixels** [comment]
Great - Thanks :) :+1:

**Comment by akoenig** [comment]
Closed in favor of: #15

**Pull request closed without merging**
